fix(API): 🧹 Retrait du code et documentation liées aux utilisateurs (login...)
signaux-faibles/opensignauxfaibles pull request #121
Opened 2020-08-12 13:26 UTC by adrienjoly

2020-08-12 15:47 UTC, adrienjoly commented on .github/workflows/js-functions.yml
> +        run: tests/test-api-swagger.sh
Note: j'ai ajouté ce test dans le workflow "js" au lieu du workflow des tests de bout en bout pour des raisons d'optimisation de la vitesse d'exécution de CI, car ces tests nécessitent node.js, or ce dernier n'est pas installé sur le workflow des tests de bout en bout.

2020-08-20 12:06 UTC, chrnin commented on dbmongo/main.go
> +	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler)) // serves interactive API documentation on http://localhost:5000/swagger/index.html
Si je ne m'abuse, l'url du endpoint dépend du paramètre APP_BIND passé dans config.toml, peut être que le commentaire peut induire en erreur avec localhost:5000.

2020-08-20 12:08 UTC, chrnin commented on .github/workflows/js-functions.yml
> +        run: tests/test-api-swagger.sh
Effectivement, le gain de temps étant assez important, ce n'est pas déconnant.

2020-08-20 12:12 UTC, chrnin requested changes
Juste le petit point sur le commentaire concernant endpoint… À voir ce que tu veux en faire.

2020-08-20 12:12 UTC, chrnin commented on dbmongo/docs/swagger/swagger.yaml
>      - Consultation des données
```suggestion
    - Export et consultation des données  
```

2020-08-20 12:31 UTC, chrnin approved these changes
Wunderbar !

2020-08-20 12:50 UTC, merged