fix(apconso): Refactoring du parseur "apconso"
signaux-faibles/opensignauxfaibles pull request #186
Opened 2020-10-12 13:04 UTC by adrienjoly

Même démarche que dans PR #174.

2020-10-13 15:46 UTC, adrienjoly commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ dbmongo/lib/apconso/main.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6324057&bid=20553576)

2020-10-13 15:52 UTC, adrienjoly commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ dbmongo/lib/apconso/main.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6324057&bid=20553576)

2020-10-13 17:11 UTC, JazzyPierrot requested changes

2020-10-13 17:11 UTC, JazzyPierrot commented on dbmongo/lib/apconso/main.go
> +			} /* else {
Le code commenté peut être supprimé. On a un event.Info final pour cela.

2020-10-13 17:11 UTC, JazzyPierrot commented on dbmongo/lib/apconso/main.go
> +	idx["Effectifs"] = misc.SliceIndex(35, func(i int) bool { return fields[i] == "EFFECTIFS" })
Je pense qu'il serait pertinent de mettre les noms des champs de l'objet golang plutôt que les noms des colonnes dans colMapping. 
ERRATUM: après vérification dans sirene on utilise les noms des colonnes, et dans bdf on utilise les noms de l'objet. Je n'ai pas vraiment d'avis sur la question.  

Sinon un détail, peut-être une petite harmonisation à faire au niveau des noms, dans sirene on a "f", dans bdf "fields", et ici "colMapping" (avec un autre objet "fields" qui  est habituellement nommé "row"), peut-être l'as-tu déjà faite dans les autres PR...

2020-10-13 17:24 UTC, JazzyPierrot approved these changes

2020-10-14 07:25 UTC, adrienjoly commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ dbmongo/lib/apconso/main.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6324057&bid=20553576)

2020-10-14 08:27 UTC, adrienjoly commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ dbmongo/lib/apconso/main.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6324057&bid=20553576)

2020-10-14 08:41 UTC, adrienjoly commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ dbmongo/lib/apconso/main.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=6324057&bid=20553576)

2020-10-14 08:43 UTC, merged