fix(reduce.algo2): Documentation des variables URSSAF
signaux-faibles/opensignauxfaibles pull request #293
Opened 2021-01-19 15:45 UTC by adrienjoly

2021-01-25 08:59 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "computed": true
Intuitivement j'ai du mal à comprendre comment ce champs peut être "computed"... L'URSSAF ne nous envoie pas une date ?

2021-01-25 09:01 UTC, chrnin approved these changes
Joli morceau !
LGTM

2021-01-25 09:04 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "description": "ratio_dette divise montant_part_ouvriere et montant_part_patronale par cotisation_moy12m.",
`ratio_dette = (montant_part_ouvriere + montant_part_patronale) / cotisation_moy12m`

Privilegier les formules au texte quand c'est un calcul simple

2021-01-25 09:05 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "description": "Survenance d'un débit d'au moins 1% des cotisations",
@arianelestrade tu comprends ce champs ? Ou alors il faudra que je demande à Elodie ou Pierre.

2021-01-25 09:05 UTC, chrnin commented on js/reduce.algo2/docs/variables.json
> +        "computed": true
En fait, l'URSSAF nous envoie un champ à son (ses… ça dépend du fichier) format, et on le transforme en date iso.

2021-01-25 09:07 UTC, chrnin commented on js/reduce.algo2/docs/variables.json
> +        "description": "Survenance d'un débit d'au moins 1% des cotisations",
Je crois que c'est une indicatrice qui signale la présence de débit au delà du seuil de 1%, c'était probablement utile du temps de la régression logistique, je ne sais pas si ça présente un intérêt avec l'algo actuel.

2021-01-25 09:08 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "description": "Survenance d'un débit d'au moins 1% des cotisations",
Ah ok je crois que c'est un impayé de plus de 1% de ce qui est dû par l'entreprise

2021-01-25 09:09 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "name": "interessante_urssaf",
je ne suis pas sur de comprendre pourquoi ce champs s'appelle comme ça...

2021-01-25 09:14 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "description": "Nombre de jours restants du délai.",
"Nombre de jours restants du délai de paiement."

2021-01-25 09:35 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "description": "Vaut 1 si cette valeur d'effectif a été reportée, pour combler une donnée manquante.",
"Reportée" == on a pris la derniere valeur connue et on l'utilise pour la periode en cours ?

2021-01-25 09:36 UTC, adrienjoly commented on js/reduce.algo2/docs/variables.json
> +        "computed": true
Voici la supposition sur laquelle je me suis appuyé: j'ai marqué comme `computed` tout champ qui n'est pas transmis _tel-quel_ du fichier source à Features.

Qu'est-ce que "computed" veut dire, de ton point de vue, Vincent ?

2021-01-25 09:37 UTC, adrienjoly commented on js/reduce.algo2/docs/variables.json
> +        "description": "ratio_dette divise montant_part_ouvriere et montant_part_patronale par cotisation_moy12m.",
Ok ! N'hésite pas à me pinger sur les autres descriptions que tu préfererais exprimer sous forme de formules.

```suggestion
        "description": "ratio_dette = (montant_part_ouvriere + montant_part_patronale) / cotisation_moy12m",
```

2021-01-25 09:38 UTC, adrienjoly commented on js/reduce.algo2/docs/variables.json
> +        "description": "Survenance d'un débit d'au moins 1% des cotisations",
N'hésite pas à proposer une formulation alternative si tu le souhaites :-) 

![image](https://user-images.githubusercontent.com/531781/105688111-810e5580-5ef9-11eb-8c14-eaa8fc32cac7.png)

2021-01-25 09:40 UTC, adrienjoly commented on js/reduce.algo2/docs/variables.json
> +        "name": "interessante_urssaf",
moi non plus...

n'hésite pas à demander des précisions à Pierre, proposer le renommage ou la suppression de champs.

2021-01-25 09:41 UTC, adrienjoly commented on js/reduce.algo2/docs/variables.json
> +        "description": "Nombre de jours restants du délai.",
```suggestion
        "description": "Nombre de jours restants du délai de paiement.",
```

2021-01-25 09:42 UTC, adrienjoly commented on js/reduce.algo2/docs/variables.json
> +        "description": "Vaut 1 si cette valeur d'effectif a été reportée, pour combler une donnée manquante.",
oui

2021-01-25 09:43 UTC, vviers requested changes
LGTM à part les 2/3 ajouts demandés :)

2021-01-25 09:44 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "description": "Vaut 1 si cette valeur d'effectif a été reportée, pour combler une donnée manquante.",
"Vaut 1 si cette valeur est absente pour la période donnée et que le dernier effectif connu a été utilisé à la place."

2021-01-25 09:50 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "computed": true
Dans mon esprit, "computed" c'était une création de nouvelle colonne / d'un champs qui n'existe pas dans la donnée source — une transformation métier

Un changement de format (e.g. parser une string `vrai` en booleen) n'était pas vraiment ce que j'imaginais comme un calcul, mais en y repensant je comprends ton parti-pris

2021-01-25 09:53 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "description": "Vaut 1 si cette valeur d'effectif a été reportée, pour combler une donnée manquante.",
```suggestion
        "description": "Vaut 1 si cette valeur est absente pour la période donnée et que le dernier effectif connu a été utilisé à la place.",
```

2021-01-25 09:56 UTC, adrienjoly commented on js/reduce.algo2/docs/variables.json
> +        "computed": true
Souhaites-tu que je refasse une passe pour mettre `computed` à `false` pour les traitements _légers_ comme celui fait sur `date_ccsf` ?

2021-01-25 10:02 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "computed": true
ça serait top, si ça ne t'embete pas trop, sinon je peux m'en occuper :)

2021-01-25 10:03 UTC, adrienjoly commented on js/reduce.algo2/docs/variables.json
> +        "computed": true
je veux bien que tu le fasses toi. ça pourrait réduire le nombre d'aller-retours.

2021-01-25 10:05 UTC, adrienjoly commented on js/reduce.algo2/docs/variables.json
> +        "computed": true
soit en commentant les lignes concernées dans le diff `variables.json`, sur la PR. soit en m'envoyant la liste des variables que tu aimerais que je passe en _transmitted_ (c.a.d. computed=false).

2021-01-25 10:15 UTC, vviers approved these changes
LGTM :)

2021-01-25 10:25 UTC, vviers commented on js/reduce.algo2/docs/variables.json
> +        "description": "true: si l'entreprise n'a pas eu de débit (dette) sur les 6 derniers mois",
```suggestion
        "description": "Règle métier URSSAF. true: si l'entreprise n'a pas eu de débit (dette) sur les 6 derniers mois. Pas utile dans les travaux de data science.",
```

2021-01-25 10:52 UTC, adrienjoly commented on js/reduce.algo2/docs/variables.json
> +        "computed": true
C'est fait et appliqué !

2021-01-25 10:52 UTC, adrienjoly commented
Merci à vous deux pour votre relecture de cette PR assez dense ! 💪

2021-01-25 10:58 UTC, merged

2021-02-04 08:45 UTC, arianelestrade commented
Désolée d'intervenir seulement maintenant, j'étais en congé, mais ça a l'air d'être un super boulot bien dense et top utile que vous faites là ! Je regarde aujourd'hui et vous fait un retour si j'ai des retours à faire (ou des questions) !